#!/bin/bash
# skript vanusemääramine
#
echo "Sisestage oma vanus"
read vanus
if test $vanus -gt 0 -a $vanus -lt 11
then 
        echo "olete laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
        echo "olete nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
        echo "olete täiskasvanu"
elif test $vanus -ge 63
then
        echo "olete senioor"
else
        echo "vigane sisend"
fi
#
#lõpp
