#!/bin/bash
#
# Ülesanne4
echo -n "Sisestage suvaline arv: "
read number
i=2

while [ $i -lt $number ]
do
  if [ `expr $number % $i` -eq 0 ]
  then
      echo "$number - ei ole algarv"
exit
  fi
  i=`expr $i + 1`
done

echo "$number - on algarv "
#
# lõpp
