#!/bin/bash
#
# kolmnurga pindala
#
echo "Sisestage kolmurga esimene külg(a)(cm):"
read a
echo "Sisestage kolmnurga teine külg(b)(cm):"
read b
echo "Sisestage kolmnurga kolmas külg(c)(cm):"
read c
#
x1=`echo "scale=2;($a+$b+$c)/2" | bc` #pool kolmnurga ümbermõõtu
x2=`echo "scale=2;sqrt ($x1*($x1-$a)*($x1-$b)*($x1-$c))" | bc` #pindala
echo "Pindala on $x2"
#
# lõpp
