#!/bin/bash
echo -n "Sisestage ridade arv: "
read rida
echo -n "Sisestage tärnide arv reas: "
read tarn
for (( i = 1; i <= rida; i++ ))
do
echo -n "$i "
for (( j = 1; j <= tarn; j++ ))
do
echo -n "*"
done
echo ""
done
#lõpp
